#!/usr/bin/python
# -*- coding: UTF-8 -*-

import os
import readline

persistent_history = os.path.join(
  os.path.expanduser('~'),
  '.lemming_history')

common_phrases = {
    '1': '%s - skopiuj',
    '2': '%s - przełącz na kopię',
    '3': '%s - usuń oryginał',
}

def rozwin_opis(odp):
    first = odp[0]
    if first in common_phrases:
        wynik = common_phrases[first] % odp[1:]
    else:
        wynik = odp
    return wynik

def main():
    readline.set_history_length(10000)
    if os.path.isfile(persistent_history):
        readline.read_history_file(persistent_history)
    while 1:
        odp = raw_input('Commit message: ')
        if odp:
            odp = rozwin_opis(odp)
            polecenie = 'git commit -m "%s"' % odp
            os.system(polecenie)
        else:
            print 'Empty string - end of work'
            break
    readline.write_history_file(persistent_history)

if __name__ == '__main__':
    main()
