#!/usr/bin/python
# -*- coding: UTF-8 -*-

import os
import readline

persistent_history = os.path.join(
    os.path.expanduser('~'),
    '.lemming_history'
)

common_phrases = {
    '1': '%s - copy',
    '2': '%s - switch to copy',
    '3': '%s - remove original',
}


def expand_phrase(message):
    prefix = message[0]
    if prefix in common_phrases:
        result = common_phrases[prefix] % message[1:]
    else:
        result = message
    return result


def history_start():
    readline.set_history_length(10000)
    if os.path.isfile(persistent_history):
        readline.read_history_file(persistent_history)


def main():
    history_start()
    while 1:
        message = raw_input('Commit message: ')
        if message:
            message = expand_phrase(message)
            command = 'git commit -m "%s"' % message
            os.system(command)
        else:
            print 'Empty string - end of work'
            break
    readline.write_history_file(persistent_history)

if __name__ == '__main__':
    main()
